# Generated by Django 3.1.4 on 2020-12-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sgalgorithmstatus',
            old_name='parent_mlalgorithm',
            new_name='parent_sgalgorithm',
        ),
    ]
